### ISSUE TITLE
老板，你的Biu我取走啦

### ISSUE THREAD

**Issue by MilkSU-Official** [Kilerd/biu#1]
风格简洁明了，真的很不错！

**Comment by Kilerd** [comment]
in github the version of this Project is still a prototype, but I have completed more than this, and I will push the newest version to the repo in 3 days.

could you tell me what blog system you used is?

I use Typecho as my blog engine, if you are using the same one, I can push the typecho theme to you directly.

**Comment by MilkSU-Official** [comment]
very grateful for your help!

but I would use Flask as server side framework, and your biu's style to my blog front-end side framework to complete my blog site.
